# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    # dummy

    steps:
    - uses: actions/checkout@v4

    - name: Fetch dependencies
      run: sudo apt update && sudo apt install -y qtbase5-dev libqt5svg5-dev

    - name: Update submodules
      run: git submodule update --init

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --verbose --config ${{env.BUILD_TYPE}}
